- hosts: all
  tasks:

    - name: Install base packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - software-properties-common
        - htop
    
    - name: Add Node PPA repo
      shell: "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -"

    - name: Install Node
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - nodejs

    - name: Configure the Yarn APT key
      apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg

    - name: Add Yarn repository
      apt_repository:
        repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
        state: present

    - name: Install Yarn
      apt: 
        pkg: yarn 
        state: present
    
    - name: Setup folders for SSL 
      file:
        path: "/etc/letsencrypt/{{ item }}"
        state: directory
      with_items:
        - accounts
        - archive
        - csr
        - keys
        - live
        - renewal
        - challenges/admin
        - challenges/fullpass
        - challenges/weekonekt
