- hosts: all
  vars_files:
    - ../vars.yml
  tasks:

    - name: Remove old release
      file:
        path: "/home/{{ app_user }}/app"
        state: "{{ item }}"
      with_items:
        - "absent"

    - name: Checkout source code
      git:
        repo: "https://github.com/cm/fullpass.git"
        dest: "/home/{{ app_user }}/app"

    - name: Set work dir
      file:
        path: "/home/{{ app_user }}/data"
        state: "{{ item }}"
      with_items:
        - absent
        - directory

    - name: Set data dirs
      file:
        path: "/home/{{ app_user }}/data/{{ item }}"
        state: "directory"
      with_items:
        - "mnesia"
        - "cluster"

    - name: Configure release
      template: 
        src: "../templates/{{ item }}"
        dest: "/home/{{ app_user }}/app/config/{{ item }}"
      with_items:
        - sys.config
        - vm.args
    
    - name: Set hosts.erlang
      template:
        src: "../templates/hosts.erlang"
        dest: "/home/{{ app_user }}/.hosts.erlang"
    
    - name: Setup convenience scripts
      template:
        src: "../templates/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: "u+rx"
      with_items:
        - attach
        - logs

    - name: Fix permissions
      file:
        path: "/home/{{ app_user }}"
        state: "directory"
        owner: "{{ app_user }}"
        group: "staff"
        recurse: yes

    - name: Make the release
      shell: "rebar3 release"
      args:
        chdir: "/home/{{ app_user }}/app"
      become: yes
      become_user: "{{ app_user }}"
    
    - name: Configure systemd
      template:
        src: "../templates/{{ app_name }}.service"
        dest: "/etc/systemd/system/{{ app_name }}.service"

    - name: Start {{ app_name }}
      service:
        name: "{{ app_name }}"
        state: "{{ item }}"
      with_items:
        - stopped
        - started
