- hosts: places
  vars_files:
    - ../vars.yml
  tasks:
    
    - name: Setup data dir
      file:
        path: /home/fullpass/data/places
        state: directory

    - name: Build Places executable
      shell: "go build -o places cmdb.go"
      args:
        chdir: /tmp/cmdb
    
    - name: Add Places to PATH
      copy:
        remote_src: yes
        src: /tmp/cmdb/places
        dest: /usr/local/bin
        mode: u+x,g+x,o+x
    
    - name: Configure Places Store Unit file
      template:
        src:  ../templates/places.service
        dest: /lib/systemd/system/places.service

    - name: Restart Places
      service:
        name: places
        state: restarted
        daemon_reload: yes
